"""datasets.original_identifier

CKAN 2.11 regenerated resource ids when datos.gob.ar migrated around 2026-07-29,
so the same file now arrives under an identifier we have never seen. Nothing
links the new id to the old one, and the catalogue grew a second copy of every
resource that was re-identified.

Measured on 2026-08-23, for `datos_gob_ar` alone: 5,406 URLs carry more than one
`source_id`, spanning 13,433 rows. **5,293 of those URL groups share a single
title** — they are one resource wearing several names, not several resources.
The 113 that differ are genuinely distinct and must not be merged.

The example that makes it plain, all three on one URL with one title:

    energia_50a81ccc-…-297c1cad25fe   2026-05-04   (our own old prefixing)
    50a81ccc-…-297c1cad25fe           2026-05-04   (the CKAN 2.10 id)
    7b366306-…-cc2aa2575043           2026-07-29   (regenerated by CKAN 2.11)

This column holds the earliest identifier we ever saw for that resource, so a
row keeps a name that survives the portal renaming it. Populating it decides
nothing: no row is merged, nothing is deleted, and the duplicates stay exactly
as they are. It only makes the question answerable — which is the part that has
been missing.

Nullable, because most rows have no reconciliation to record and a value there
would be an invention.

Revision ID: 0061
Revises: 0060
"""

from alembic import op

revision = "0061"
down_revision = "0060"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE datasets ADD COLUMN IF NOT EXISTS original_identifier TEXT")
    # The lookup this exists for: "everything that is really this resource".
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_datasets_original_identifier
        ON datasets (original_identifier)
        WHERE original_identifier IS NOT NULL
        """
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_datasets_original_identifier")
    op.execute("ALTER TABLE datasets DROP COLUMN IF EXISTS original_identifier")
